<?php 
    define("USER_CREATED_SUCCESSFULLY", "USER_CREATED_SUCCESSFULLY");
    define("USER_UPDATED", "USER_UPDATED");
    define("PASSWORD_IS_CHANGED", "PASSWORD_IS_CHANGED");
    define("PASSWORDS_ARE_NOT_IDENTICAL", "PASSWORDS_ARE_NOT_IDENTICAL");
    define("EMAIL_ALREADY_TAKEN", "EMAIL_ALREADY_TAKEN");
    define("INCORRECT_CREDENTIALS", "INCORRECT_CREDENTIALS");
    define("NO_CHANGE", "NO_CHANGE");
    define("FAILED_TO_UPDATE", "FAILED_TO_UPDATE");
    define("FAILED_TO_CREATE", "FAILED_TO_CREATE");
    define("CANT_RETURN_USER", "CANT_RETURN_USER");
    define("CANT_RETURN_API_KEY", "CANT_RETURN_API_KEY");
?>